//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagerApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueInfo
    {
        public string Id { get; set; }
        public string IdProduct { get; set; }
        public string IDIssue { get; set; }
        public int IDCustomer { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> IssuePrice { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Issue Issue { get; set; }
        public virtual Product Product { get; set; }
    }
}
