//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagerApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptInfo
    {
        public string Id { get; set; }
        public string IdProduct { get; set; }
        public string IdReceipt { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> ReceiptPrice { get; set; }
        public Nullable<double> IssuePrice { get; set; }
        public string Status { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
